export const LOCATIONS_DATA = [
  {
    dealer_id: 'DLR001',
    dealer_name: 'Royal Enfield Andheri',
    area: 'Andheri East',
    city: 'Mumbai',
    state: 'Maharashtra',
  },
  {
    dealer_id: 'DLR002',
    dealer_name: 'Royal Enfield Baner',
    area: 'Baner',
    city: 'Pune',
    state: 'Maharashtra',
  },
  {
    dealer_id: 'DLR003',
    dealer_name: 'Royal Enfield Wakad',
    area: 'Wakad',
    city: 'Pune',
    state: 'Maharashtra',
  },
  {
    dealer_id: 'DLR004',
    dealer_name: 'Royal Enfield Thane',
    area: 'Ghodbunder Road',
    city: 'Thane',
    state: 'Maharashtra',
  },
  {
    dealer_id: 'DLR005',
    dealer_name: 'Royal Enfield Vashi',
    area: 'Vashi Sector 17',
    city: 'Navi Mumbai',
    state: 'Maharashtra',
  },
  {
    dealer_id: 'DLR006',
    dealer_name: 'Royal Enfield Indiranagar',
    area: 'Indiranagar',
    city: 'Bengaluru',
    state: 'Karnataka',
  },
  {
    dealer_id: 'DLR007',
    dealer_name: 'Royal Enfield Whitefield',
    area: 'Whitefield',
    city: 'Bengaluru',
    state: 'Karnataka',
  },
  {
    dealer_id: 'DLR008',
    dealer_name: 'Royal Enfield Koramangala',
    area: 'Koramangala 5th Block',
    city: 'Bengaluru',
    state: 'Karnataka',
  },
  {
    dealer_id: 'DLR009',
    dealer_name: 'Royal Enfield Anna Nagar',
    area: 'Anna Nagar',
    city: 'Chennai',
    state: 'Tamil Nadu',
  },
  {
    dealer_id: 'DLR010',
    dealer_name: 'Royal Enfield OMR',
    area: 'Sholinganallur',
    city: 'Chennai',
    state: 'Tamil Nadu',
  },
  {
    dealer_id: 'DLR011',
    dealer_name: 'Royal Enfield Velachery',
    area: 'Velachery',
    city: 'Chennai',
    state: 'Tamil Nadu',
  },
  {
    dealer_id: 'DLR012',
    dealer_name: 'Royal Enfield Banjara Hills',
    area: 'Banjara Hills',
    city: 'Hyderabad',
    state: 'Telangana',
  },
  {
    dealer_id: 'DLR013',
    dealer_name: 'Royal Enfield Gachibowli',
    area: 'Gachibowli',
    city: 'Hyderabad',
    state: 'Telangana',
  },
  {
    dealer_id: 'DLR014',
    dealer_name: 'Royal Enfield Hitech City',
    area: 'Madhapur',
    city: 'Hyderabad',
    state: 'Telangana',
  },
  {
    dealer_id: 'DLR015',
    dealer_name: 'Royal Enfield Saket',
    area: 'Saket',
    city: 'New Delhi',
    state: 'Delhi',
  },
  {
    dealer_id: 'DLR016',
    dealer_name: 'Royal Enfield Karol Bagh',
    area: 'Karol Bagh',
    city: 'New Delhi',
    state: 'Delhi',
  },
  {
    dealer_id: 'DLR017',
    dealer_name: 'Royal Enfield Rohini',
    area: 'Rohini Sector 10',
    city: 'New Delhi',
    state: 'Delhi',
  },
  {
    dealer_id: 'DLR018',
    dealer_name: 'Royal Enfield Salt Lake',
    area: 'Salt Lake Sector V',
    city: 'Kolkata',
    state: 'West Bengal',
  },
  {
    dealer_id: 'DLR019',
    dealer_name: 'Royal Enfield Howrah',
    area: 'Shibpur',
    city: 'Howrah',
    state: 'West Bengal',
  },
  {
    dealer_id: 'DLR020',
    dealer_name: 'Royal Enfield Park Street',
    area: 'Park Street',
    city: 'Kolkata',
    state: 'West Bengal',
  },
];
